[package]
name = "akai"
edition = "2021"
version = "0.1.0"
license = "Apache-2.0"
description = "Next-generation, functional and simple ID system"

[dependencies]
hex = "0.4.3"
rand = "0.8.5"
regex = "1.10.2"
